trigger:
- main

pool:
  name: default # This is your agent pool name
  demands:
    - agent.name -equals third-agent # This specifies your agent

jobs:
- job: InstallNode
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

